plants/urls.py
from django.conf.urls import patterns, url
from plants.views import *

urlpatterns = patterns('',
    url(r'^plant-list', PlantCatListView.as_view()),
    url(r'^category/(?P<cat>[-\w]+)/(?P<page>[\d]*)/$', CustomCatView.as_view()),
    url(r'^category/(?P<cat>[-\w]+)/$', CustomCatView.as_view()),
    url(r'^search/(?P<page>[\d]*)/$', CustomSearchView.as_view()),
    url(r'^search/$', CustomSearchView.as_view()),
    url(r'(?P<cat>[-\w]*)/(?P<slug>[-\w]+)/$', PlantDetailView.as_view()),
    url(r'^category/$', PlantCatListView.as_view()),
    url(r'^autocomplete/$', autocompleteModel),
    (r'^$', PlantCatListView.as_view())
)

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

plants/models.py
from django.db import models
# from model_utils.managers import InheritanceManager
from django.http import HttpRequest
from django.template.defaultfilters import slugify
from taggit.managers import TaggableManager

class Category(models.Model):
    category = models.CharField(max_length=128)
    slug = models.SlugField(editable=False)

    def __unicode__(self):
        return self.category

    class Meta:
        ordering = ('category',)
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.category)

        super(Category, self).save(*args, **kwargs)


class Color(models.Model):
    color = models.CharField(max_length=64)

    def __unicode__(self):
        return self.color

    class Meta:
        ordering = ('color',)

class Light(models.Model):
    light=models.CharField(max_length=64)

    def __unicode__(self):
        return self.light

class Season(models.Model):
    season=models.CharField(max_length=16)

    def __unicode__(self):
        return self.season

class Attracts(models.Model):
    attracts=models.CharField(max_length=64)

    def __unicode__(self):
        return self.attracts


class Plant(models.Model):

    scientific_name = models.CharField(max_length=128, unique=True)
    genus = models.CharField(max_length=64)
    species = models.CharField(max_length=64, blank=True)
    update_time = models.DateTimeField(auto_now=True)
    update_by = models.CharField(max_length=128)
    comment = models.TextField(blank=True)
    internal_comment = models.TextField(blank=True)
    slug = models.SlugField(blank=True,editable=False)
    tags = TaggableManager(blank=True)

    updated = models.BooleanField(default=False)
    drought_tolerant = models.BooleanField(default=False)

    search_flower_color = models.ManyToManyField(Color, related_name='plant_flower_color', blank=True)
    search_leaf_color = models.ManyToManyField(Color, related_name='plant_leaf_color', blank=True)
    search_light = models.ManyToManyField(Light, blank=True)
    search_season = models.ManyToManyField(Season, blank=True)
    attracts = models.ManyToManyField(Attracts, blank=True)
    category = models.ManyToManyField(Category)

    height = models.CharField(max_length=128, blank=True)
    width = models.CharField(max_length=128, blank=True)
    size = models.CharField(max_length=128, blank=True)
    depth = models.CharField(max_length=128, blank=True)
    space = models.CharField(max_length=128, blank=True)
    growth_rate = models.CharField(max_length=128, blank=True)
    climbing_method = models.CharField(max_length=128, blank=True)
    life_cycle = models.CharField(max_length=128, blank=True)

    site = models.TextField(blank=True)
    light = models.CharField(max_length=256, blank=True)
    soil = models.CharField(max_length=256, blank=True)
    exposure = models.CharField(max_length=256, blank=True)
    hardiness = models.CharField(max_length=256, blank=True)
    propagation = models.CharField(max_length=256, blank=True)

    regions = models.CharField(max_length=256, blank=True)
    zones = models.CharField(max_length=256, blank=True)
    habit = models.CharField(max_length=256, blank=True)

    organ = models.CharField(max_length=256, blank=True)
    fruit = models.CharField(max_length=256, blank=True)
    leaf = models.TextField(blank=True)
    foliage = models.TextField(blank=True)
    flower = models.TextField(blank=True)
    flower_color = models.CharField(max_length=256, blank=True)
    color = models.CharField(max_length=256, blank=True)
    fronds = models.TextField(blank=True)
    texture = models.CharField(max_length=256, blank=True)
    form = models.CharField(max_length=256, blank=True)
    sub_type = models.CharField(max_length=256, blank=True)
    fragrance = models.CharField(max_length=256, blank=True)
    inflorescence = models.CharField(max_length=256, blank=True)

    season = models.CharField(max_length=256, blank=True)
    flowering_period = models.CharField(max_length=256, blank=True)
    storage = models.TextField(blank=True)
    usage = models.CharField(max_length=256, blank=True)

    # poison
    family = models.CharField(max_length=256, blank=True)
    description = models.TextField(blank=True)
    origin = models.CharField(max_length=256, blank=True)
    distribution = models.CharField(max_length=256, blank=True)
    found = models.CharField(max_length=256, blank=True)
    mode = models.CharField(max_length=256, blank=True)
    poison_part = models.TextField(blank=True)
    symptoms = models.TextField(blank=True)
    edibility = models.TextField(blank=True)
    toxic_principle = models.TextField(blank=True)
    severity = models.TextField(blank=True)


    # objects = InheritanceManager()

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            if self.scientific_name.__len__() > 49:
                sci_name = self.scientific_name[:49]
            else:
                sci_name = self.scientific_name
            self.slug = slugify(sci_name)

        self.updated = True

        super(Plant, self).save(*args, **kwargs)


    def common_names(self):
        return ', '.join([c.common_name for c in self.commonname_set.all()])

    def cultivars(self):
        return ', '.join([c.cultivar for c in self.cultivar_set.all()])

    def categories(self):
        return ', '.join([c.category for c in self.category.all()])

    def old_urls(self):
        return ', '.join([c.old_url for c in self.oldurl_set.all()])

    def category_links(self):
        urls = []
        for c in self.category.all():
            urls.append('<a href="/plants/category/%s"/>%s</a>' % (c.category, c.category))
        return ', '.join(urls)

    def images(self):
        imgs = ' /><img src="'.join([i.img_url for i in self.plantimage_set.all()])
        return '<img src="'+imgs+' />'

    def get_fields(self):
        # return [(field.name, field.value_to_string(self)) for field in self._meta.fields]
        fields=[('Common Name(s)', self.common_names()),
                ('Cultivar(s)', self.cultivars()),
                ('Categories', self.categories()),
                ('Comment', self.comment),
                ('Description', self.description),
                ('Season', self.season),
                ('Light', self.light),
                ('Color', self.color),
                ('Height', self.height),
                ('Space', self.space),
                ('Flowering Period', self.flowering_period),
                ('Flower Color', self.flower_color),
                ('Depth', self.depth),
                ('Usage', self.usage),
                ('Organ', self.organ),
                ('Hardiness', self.hardiness),
                ('Storage', self.storage),
                ('Foliage', self.foliage),
                ('Flower', self.flower),
                ('Zones', self.zones),
                ('Habit', self.habit),
                ('Fronds', self.fronds),
                ('Site', self.site),
                # 'rate',
                ('Size', self.size),
                ('Texture', self.texture),
                ('Form', self.form),
                ('Propagation', self.propagation),
                ('Exposure', self.exposure),
                ('Fruit', self.fruit),
                ('Soil', self.soil),
                ('Inflorescence', self.inflorescence),
                ('Regions', self.regions),
                ('Family', self.family),
                ('Origin', self.origin),
                ('Distribution', self.distribution),
                ('Poison Part', self.poison_part),
                ('Poison Delivery Mode', self.mode),
                ('Symptoms', self.symptoms),
                ('Edibility', self.edibility),
                ('Toxic Principle', self.toxic_principle),
                ('Severity', self.severity),
                ('Found in', self.found),
                ('Type', self.sub_type),
                ('Fragrance', self.fragrance),
                ('Width', self.width),
                ('Growth Rate', self.growth_rate),
                ('Leaf', self.leaf),
                ('Climbing Method', self.climbing_method),
                ('Life Cycle', self.life_cycle),
                # ('Attracts Songbirds', self.attracts_songbirds),
                ('Tags', ', '.join([t.name for t in self.tags.all()])), ]

        if self.category.all().__len__() == 1:
            fields[2] = ('Category', self.categories())


        return fields

    def verbose_name(self):
        return self._meta.verbose_name

    def get_absolute_url(self):
        return '/plants/all/%s/' % (self.slug)

    def __unicode__(self):
        return self.scientific_name

class PlantImage(models.Model):
    plant = models.ForeignKey(Plant)
    img_url = models.URLField()
    alt_text = models.CharField(max_length=64)
    width = models.IntegerField(blank=True)
    height = models.IntegerField(blank=True)
    thumbnail = models.BooleanField(default=False)
    def __unicode__(self):
        return self.img_url

class CommonName(models.Model):
    plant = models.ForeignKey(Plant)
    common_name = models.CharField(max_length=128, null=True)

    def __unicode__(self):
        return self.common_name

class OldUrl(models.Model):
    plant = models.ForeignKey(Plant)
    old_url = models.URLField(max_length=128, null=True)

    def __unicode__(self):
        return self.old_url

class Cultivar(models.Model):

    plant = models.ForeignKey(Plant)
    cultivar = models.CharField(max_length=128)

    def __unicode__(self):
        return self.cultivar

plants/templates/plants/all.html
{% extends "plants/base.html" %}
{% block title %}{{  plant.scientific_name }}{% endblock %}

{% block content %}
<ul>
{#{% for key, value in categories.items %}#}
{#    <li><a href="/plants/{{ value }}">{{ key }}</a></li>#}
{#{%  endfor %}#}

<li><a href="/plants/annual/">Annuals</a></li>
<li><a href="/plants/carnivorous/">Carnivorous Plants</a></li>
<li><a href="/plants/fern/">Ferns</a></li>
<li><a href="/plants/groundcover/">Groundcover</a></li>
<li><a href="/plants/herb/">Herbs</a></li>
<li><a href="/plants/native/">Native Plants</a></li>
<li><a href="/plants/ornamentalgrass/">Ornamental Grasses</a></li>
<li><a href="/plants/bulbperennial/">Perennial Bulbs</a></li>
<li><a href="/plants/perennial/">Perennials</a></li>
<li><a href="/plants/poison/">Poisonous Plants</a></li>
<li><a href="/plants/rose/">Roses</a></li>
<li><a href="/plants/shrub/">Shrubs</a></li>
<li><a href="/plants/bulbspring/">Spring Bulbs</a></li>
<li><a href="/plants/bulbsummer/">Summer Bulbs</a></li>
<li><a href="/plants/tree/">Trees</a></li>
<li><a href="/plants/vine/">Vines</a></li>
<li><a href="/plants/watergarden/">Water Gardens</a></li>
<li><a href="/plants/wildflower/">Wildflowers</a></li>

</ul>
{% endblock %}

plants/templates/plants/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="google-site-verification" content="UzRsUPNUyEfN2F8Sk50Hv0hjwKo3Q4o6cFTRpT6Sfs4" />
    <link rel="stylesheet" href="{%  static "plants/css/base.css" %}" />
    <link rel="stylesheet" href="{%  static "plants/css/layout.css" %}" />
    <link rel="stylesheet" href="{%  static "plants/css/skeleton.css" %}" />
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    {% block canonical %}{% endblock %}
    <title>{% block title %}Consumer Fact Sheets{% endblock %}</title>
<link href="http://www.ces.ncsu.edu/favicon.ico" rel="Shortcut Icon" type="image/x-icon">
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-32659497-3', 'ncsu.edu');
  ga('send', 'pageview');

</script>
</head>

<body>
    <div class="container">

    <div id="spinner" class="spinner" style="display:none;">
        <img id="img-spinner" src="/static/plants/css/images/ajax-loader.gif" alt="Loading"/>
    </div>

        <div class="sixteen columns">

            <div id="ncce-logo-header" class="eleven columns">
                <div id="ncce-ncsu-brick">
                    <img alt="NC State University Brick Logo" src="http://www.ces.ncsu.edu/images/ncsu_red_brick.png" height="22" width="142">
                </div>
                <img alt="NCCE Logo" src="http://www.ces.ncsu.edu/images/logos/nc-cooperative-extension-logo.png">
            </div>

            <div id="search_div" class="five columns">
                <form class="search_form" action="/plants/search/" method="get" >
{#                    {% if error %}#}
{#                        <p style="color: red;">Please submit a search term.</p>#}
{#                    {% endif %}#}
                    <div class="search_error" {% if error %}style="display: block;"{% endif %}>Please submit a search term.</div>
                    <input type="submit" id="search_submit" class="search" value="Search" />
                    <input type="text" name="q" id="search_input" value="{{ search_query|default_if_none:"" }}" />
                </form>
            </div>

        </div>

        <div id="content" class="sixteen columns">
            <div class="plant_detail">
                {% block content %}{% endblock %}
            </div>
        </div>

    </div>
</body>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script src="{%  static "plants/js/main.js" %}"></script>
</html>

plants/templates/plants/category_index.html
{% extends "plants/base.html" %}

{% block title %}{{  plant.scientific_name }}{% endblock %}

{% block content %}

<div class="breadcrumb_container"><a href="/plants/plant-list">Plants</a></div>

{% if plant_list %}
    <ul>
    {% for plant in plant_list %}
        <li><a href="{{ plant.get_absolute_url }}">{{ plant.scientific_name }}</a> | {{ plant.common_names }}<li>
    {% endfor %}
    </ul>
{% else %}
    <p>No plants are available.</p>
{% endif %}

{% endblock %}

plants/templates/plants/detail.html
{% extends "plants/base.html" %}
{% load plant_extras %}

{% block title %}{{  plant.scientific_name }}{% endblock %}
{% block canonical %}<link rel="canonical" href="{{ plant.get_absolute_url }}"/>{% endblock %}

{% block content %}
    <div class="breadcrumb_container"><a href="/plants/plant-list">Plants</a>{% if category %} > <a href="/plants/category/{{ category.slug }}/">{{ category.category }}</a>{% endif %} > {{  plant.scientific_name }}</div>


<div id="left_col">

<div class="plant_details">
<h1>{{  plant.scientific_name }}</h1>
{% if poison %}
     <div class="poison-warning">This plant has poison characteristics. See below.</div>
{% endif %}
    <dl>
    {% for name, value in plant.get_fields %}
      {% if value %}
        <dt class="key key-{{ name|slugify }}">{{ name }}:</dt><dd class="value value-{{ name|slugify }}">{{ value|safe }}</dd>
      {% endif %}
    {% endfor %}
    </dl>

<p class='qr_code'>
    <img src="{{plant_url|qr:"120x130"}}" />
</p>

<p class='plant_id'>
    NCCES plant id: {{ plant.id }}
</p>

</div>
{#<div class="detail_bottom"></div>#}
</div>

<div id="right_col">
        <!--<dt>Images</dt>-->

        {% for i in plant.plantimage_set.all %}
        <div class="img_container"><img class="plant_image" src="{{  i.img_url }}" alt="{{ i.alt_text }}" /><span class="caption">{{ i.alt_text }}</span></div>
        {% endfor %}

</div>


{% endblock %}

plants/templates/plants/index.html
{% extends "plants/base.html" %}

{% block title %}{{  plant.scientific_name }}{% endblock %}

{% block content %}

<div class="breadcrumb_container"><a href="/plants/plant-list">Plants</a></div>

{% if plant_list %}
    {% regroup plant_list by category.category as category_list %}
    {{ category_list }}
    <ul>
    {% for cat in category_list %}
        <li>{{ cat.grouper }}
            <ul>
                {% for plant in plant_list.list %}
                    <li><a href="/plants/{{ plant.slug }}/">{{ plant.scientific_name }}</a> | {{ plant.common_names }}</li>
                {% endfor %}
            </ul>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No plants are available.</p>
{% endif %}

{% endblock %}

plants/templates/plants/index2.html
{% extends "plants/base.html" %}

{% block content %}

<div class="breadcrumb_container"><a href="/plants/plant-list">Plants</a></div>

<div class="plant_list categories">

{#<ul class="cat_list">#}
{#{% for  cat in plant_cat_list %}#}
{##}
{#    <li><a href="/plants/category/{{ cat.slug }}">{{ cat.category }}</a></li>#}
{##}
{#{% endfor %}#}
{#</ul>#}

<ul class="cat_list">

{% for cat in plant_cat_list %}
{% if forloop.counter == 10 or forloop.counter == 20 %}
</ul>
<ul class="cat_list">
{% endif %}
    <li><a href="/plants/category/{{ cat.slug }}">{{ cat.category }}</a></li>
{% endfor %}

<li><a href="/plants/category/all">All Plants</a></li>
</ul>


</div>

<div class="img_container cat_page"><img class="plant_image" src="/static/plants/css/images/lantana_camara.jpg" /></div>

{% endblock %}

plants/templates/plants/left_nav.html
{% load plant_extras %}
    <div class="three columns" id ="left_nav">
    <h3>Navigate</h3>
    <span class="nav_toggle hide">hide</span>
    <span class="nav_toggle show">show</span>
    <ul class="nav_ul">
    {% if plant_nav.category %}
        <li>Categories</li>
            <ul>
        {% for c in plant_nav.category %}
            <li>{{ c|safe }}</li>
        {% endfor %}
            </ul>
    {% endif %}

    {% if plant_nav.seasons %}
        <li>Seasons</li>
            <ul>
        {% for s in plant_nav.seasons %}
            <li>{{ s|safe }}</li>
        {% endfor %}
            </ul>
    {% endif %}

    {% if plant_nav.height %}
        <li>Height</li>
            <ul>
        {% for s in plant_nav.height %}
            <li>{{ s|safe|fix_ft_in }}</li>
        {% endfor %}
            </ul>
    {% endif %}

    {% if plant_nav.light %}
        <li>Light</li>
            <ul>
        {% for s in plant_nav.light %}
            <li>{{ s|safe }}</li>
        {% endfor %}
            </ul>
    {% endif %}

    {% if plant_nav.attracts %}
        <li>Attracts</li>
            <ul>
        {% for s in plant_nav.attracts %}
            <li>{{ s|safe }}</li>
        {% endfor %}
            </ul>
    {% endif %}

    {% if plant_nav.flower_color %}
        <li>Flower Color</li>
            <ul>
        {% for s in plant_nav.flower_color %}
            <li>{{ s|safe }}</li>
        {% endfor %}
            </ul>
    {% endif %}

    {% if plant_nav.leaf_color %}
        <li>Leaf Color</li>
            <ul>
        {% for s in plant_nav.leaf_color %}
            <li>{{ s|safe }}</li>
        {% endfor %}
            </ul>
    {% endif %}



    </ul>
    <button id="hide_nav">Done</button>
    </div>

plants/templates/plants/plant_index.html
{% extends "plants/base.html" %}
{% load plant_extras %}

{% block title %}{{ category|default_if_none:"Search Results" }}{% endblock %}

{% block content %}
    <div class="breadcrumb_container">
    <div class="search_sort_container">
        <label for="search_sort">Sort by:</label>
        <select id="search_sort" name="search_sort">
            <option value="scientific_name">Scientific Name</option>
            <option value="common_name">Common Name</option>
        </select>
    </div>
    {% if search %}
        <a href="/plants/plant-list">Plants</a> > Search > <strong>{{ search_query }}</strong>
    {% else %}
        <a href="/plants/plant-list">Plants</a> > <a href="/plants/category/{{ category.slug }}">{{ category.category }}</a>
    {% endif %}

        {% for q, i in query_dict.items %}
            {% if q != 's'  and q != 'q'%}
                {% if q != 'height' %}
                    > {{ q|deslug }} = {{ i|deslug }}
                {% else %}
                    > {{ q|deslug }} = {{ i }}
                {% endif %}
            {% endif %}
        {% endfor %}

        {{ plant_count_results }}

    </div>

<div class="">
{% include 'plants/left_nav.html' %}
    <div class="columns" id="plant-table-div">
    {% if plant_list %}

        {% if plant_count > 24 %}

            <table class="plant_list_table">
            <tr>
                <th class="th-sci-name{% if query_dict.s != 'common_name' %} sorted{% endif %}">Scientific Name</th>
                <th class="th-comm-name{% if query_dict.s == 'common_name' %} sorted{% endif %}">Common Name(s)</th>
                <th class="th-cat">Plant Category</th>
                <th class="th-img">Image</th>
            </tr>
            {% for plant in plant_list %}
                <tr>
                    <td class="th-sci-name {% cycle '' 'row-gray' as rowcolors %}"><a href="/plants/{{ category_slug|default_if_none:"all" }}/{{ plant.slug }}">{{ plant.scientific_name }}</a></td>
                    <td class="td-comm-name {{ rowcolors }}">{{ plant.common_names|default_if_none:""|safe }}</td>
                    <td class="td-cat {{ rowcolors }}">{{ plant.categories|safe }}</td>
                    <td class="td-img {{ rowcolors }}"><a href="/plants/{{ category_slug|default_if_none:"all" }}/{{ plant.slug }}"><img src="{{ plant.img|default_if_none:"/static/plants/css/images/plant_img_not_found.png"|safe }}" height="40" /></a></td>
                </tr>
            {% endfor %}
            </table>

        {% else %}

        <div id="plant_grid">
        {% for plant in plant_list %}
            {% if forloop.counter0|divisibleby:3 %}
            <div class="plant_grid_row">
            {% endif %}
            <div class="plant_grid_item">
                <h3 class=""><a href="/plants/{{ category_slug|default_if_none:"all" }}/{{ plant.slug }}">{{ plant.scientific_name }}</a></h3>
                <a href="/plants/{{ category_slug|default_if_none:"all" }}/{{ plant.slug }}"><img src="{{ plant.img|default_if_none:"/static/plants/css/images/plant_img_not_found.png"|safe }}" width="72" style="float:right" /></a>
                <dl>
                    <dt>Common Name(s)</dt>
                    <dd>{{ plant.common_names|default_if_none:""|safe }}</dd>
                    <dt>Category</dt>
                    <dd>{{ plant.categories|safe }}</dd>
                </dl>
            </div>
            {% if forloop.counter|divisibleby:3 %}
            </div>
            {% endif %}
        {% endfor %}

        {% endif %}

    {% else %}
        <p>No plants are available.</p>
    {% endif %}

    {% if plant_list.has_other_pages %}

        <div class="pagination">
        {% if plant_list.has_previous %}
            <span class="previous"><a href="{{ link_address }}{{plant_list.previous_page_number }}/?{{ query_params }}"><< previous</a></span>
        {% endif %}
        {% for page in plant_list.paginator.page_range %}
            <a {% if page == plant_list.number %} class="selected" {% endif %} href="{{ link_address }}{{ page }}/?{{ query_params }}">{{ page }}</a>
        {% endfor %}

        {% if plant_list.has_next %}
            <span class="next"><a href="{{ link_address }}{{plant_list.next_page_number }}/?{{ query_params }}">next >></a></span>
        {% endif %}
        </div>

    {% endif %}
    </div>
</div>

{% endblock %}

plants/templates/plants/search_results.html
{% extends "plants/base.html" %}

{% block title %}{{  plant.scientific_name }}{% endblock %}

{% block content %}

<div class="breadcrumb_container"><a href="/plants/plant-list">Plants</a> > Search Results</div>

{% if plant_list %}

    <ul>
    {% for plant in plant_list %}
        <li><a href="/plants/{{ plant.get_class }}/{{ plant.slug }}/">{{ plant.scientific_name }}</a> | {{ plant.common_names }} | {{ plant.category_links|safe }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No plants are available.</p>
{% endif %}

{% endblock %}